FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
COPY app.py .
COPY aqi_classifier.pkl .
COPY weather_image_classifier.h5 . 
COPY predict_7days_model.h5 .
COPY scaler.pkl .
COPY scaler_forecast_aqi.pkl .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir gunicorn

EXPOSE 5000

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]
